#######################################################################################################
#    _  __  _               _           _    _                      _                                 #
#   | |/ / (_)             | |         | |  | |                    | |                                #
#   | ' /   _   _ __     __| |   __ _  | |__| |   __ _   _ __    __| |   ___    ___    _ __    ___    #
#   |  <   | | | '_ \   / _` |  / _` | |  __  |  / _` | | '__|  / _` |  / __|  / _ \  | '__|  / _ \   #
#   | . \  | | | | | | | (_| | | (_| | | |  | | | (_| | | |    | (_| | | (__  | (_) | | |    |  __/   #
#   |_|\_\ |_| |_| |_|  \__,_|  \__,_| |_|  |_|  \__,_| |_|     \__,_|  \___|  \___/  |_|     \___|   #
#                                                                                                     #
#######################################################################################################

#Set possible spawn locations for the auto tp on death function
teleport-x-positive: 1000  # Maximum positive X coordinate
teleport-x-negative: -1000 # Minimum negative X coordinate
teleport-z-positive: 1000  # Maximum positive Z coordinate
teleport-z-negative: -1000 # Minimum negative Z coordinate

#Enable or disable the /khctoggle command. If set to false, players will not be able to toggle the auto teleport feature.
khc-toggle-enabled: true

#Enable or disable the need for the player to be an admin to use the /khctoggle command.
khc-toggle-admin-only: true